version: "3"
services:
  nginx:
    image: "nginx" 
    container_name: boke-admin
    build: .
    volumes:
       - ./dist:/usr/share/nginx/html/
       - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "8136:8136"
